"""
Public interface contracts for TraceRepository and EvaluationRepository.

This file is a CONTRACT SPECIFICATION, not implementation.
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING
from uuid import UUID

if TYPE_CHECKING:
    from data_model import TraceRecord, EvaluationResult  # type: ignore[import]


class TraceRepositoryContract:
    """
    Repository. Reads bot interaction traces from Langfuse.

    Delegates to LangfuseClient (Singleton) for the underlying SDK connection.
    Never exposes raw Langfuse API responses — all results are TraceRecord instances (FR-014).

    Usage:
        from deepeval_platform.repositories import TraceRepository
        repo = TraceRepository()
        traces = repo.get_by_bot(bot_id="my-bot")
        traces = repo.get_by_session(session_id="sess-123")
        traces = repo.get_by_date_range(bot_id="my-bot", start=dt1, end=dt2)
    """

    def get_by_bot(self, bot_id: str) -> list["TraceRecord"]:
        """
        Return all traces for `bot_id`.

        Returns [] if no traces match (no error) (FR-013).

        Raises:
            TraceRepositoryError: if Langfuse connection is unavailable (FR-013).
        """
        ...

    def get_by_session(self, session_id: str) -> list["TraceRecord"]:
        """
        Return all traces for `session_id`.

        Returns [] if no traces match.

        Raises:
            TraceRepositoryError: if Langfuse connection is unavailable.
        """
        ...

    def get_by_date_range(
        self,
        bot_id: str,
        start: datetime,
        end: datetime,
    ) -> list["TraceRecord"]:
        """
        Return traces for `bot_id` within [start, end] (UTC).

        Returns [] if no traces match.

        Raises:
            TraceRepositoryError: if Langfuse connection is unavailable.
        """
        ...


class EvaluationRepositoryContract:
    """
    Repository. Persists evaluation results to Supabase (evaluation_results table).

    Uses Supabase Python SDK (supabase>=2.0.0) internally.
    UUID is generated by the application before insert (FR-015).
    org_id is always included in the insert, even if None (FR-016).
    Write failures raise RepositoryError — no silent data loss (FR-017).

    Usage:
        from deepeval_platform.repositories import EvaluationRepository
        repo = EvaluationRepository()
        result_id = repo.save(result)          # returns UUID known before insert
        record = repo.get_by_id(result_id)
        records = repo.get_by_bot(bot_id="my-bot", date=datetime.now())
    """

    def save(self, result: "EvaluationResult") -> UUID:
        """
        Persist `result` to the evaluation_results table.

        The result.id (UUID) is generated by the caller before this call.
        Returns result.id so callers can reference it without a DB round-trip.

        Raises:
            RepositoryError: on write failure (FR-017).
        """
        ...

    def get_by_id(self, result_id: UUID) -> "EvaluationResult":
        """
        Retrieve an evaluation result by its UUID primary key.

        Raises:
            RepositoryError: if record not found or DB unavailable.
        """
        ...

    def get_by_bot(
        self,
        bot_id: str,
        date: datetime | None = None,
    ) -> list["EvaluationResult"]:
        """
        Return evaluation results for `bot_id`, optionally filtered by `date` (UTC day).

        Returns [] if no records match.

        Raises:
            RepositoryError: on DB failure.
        """
        ...


class TraceRepositoryError(Exception):
    """Raised on Langfuse connectivity failure during trace reads."""


class RepositoryError(Exception):
    """Raised on Supabase write or read failure."""
