bots:
  test_rag_bot:
    bot_type: rag
    platform: flowise
    field_mapping:
      input: input.data.question
      output: output.data.answer
      context: output.data.retrieved_contexts
      expected_output: metadata.expected_answer
  test_agent_bot:
    bot_type: agent
    platform: langchain
    field_mapping:
      input: input.data.messages.0.content
      output: output.data.messages.-1.content
      tools_called: output.data.tool_calls
      tools_called_item:
        name: tool_name
        input_parameters: arguments
        output: result
  test_conversation_bot:
    bot_type: conversation
    platform: flowise
    field_mapping:
      messages: output.data.history
      messages_item:
        role: role
        content: text
